-- =====================================================================
-- FrogPlanner — Phase 4 SQL Schema (Upcoming Tasks)
-- Run this entire script in your Supabase SQL Editor
-- ( https://supabase.com/dashboard/project/<your-project>/sql/new )
-- =====================================================================

-- ── STEP 1: Upcoming Tasks Table ───────────────────────────────────────
-- Uses autoincrementing serial integer IDs.
-- Scoped per user via FK to public.users.
CREATE TABLE IF NOT EXISTS public.upcoming_tasks (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    description  TEXT NOT NULL,
    duration     VARCHAR(50) NOT NULL, -- e.g., 'Morning', 'Afternoon', 'Evening', 'Night'
    category     VARCHAR(100) NOT NULL,
    priority     VARCHAR(50) DEFAULT '', -- 'Frog' or empty
    task_date    DATE NOT NULL,
    status       VARCHAR(50) DEFAULT 'Pending' NOT NULL, -- 'Pending', 'Completed'
    remarks      TEXT DEFAULT '',
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Index for fetching a user's upcoming tasks quickly
CREATE INDEX IF NOT EXISTS idx_upcoming_tasks_user_id
    ON public.upcoming_tasks (user_id);

-- ── STEP 2: Row-Level Security ─────────────────────────────────────────
-- Disable RLS to match existing Phase 1, 2, and 3 app-level auth pattern.
ALTER TABLE public.upcoming_tasks DISABLE ROW LEVEL SECURITY;

-- ── STEP 3: Verify the setup ───────────────────────────────────────────
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'upcoming_tasks'
ORDER BY ordinal_position;
