-- =====================================================================
-- FrogPlanner — Phase 3 SQL Schema (Projects & Project Tasks)
-- Run this entire script in your Supabase SQL Editor
-- ( https://supabase.com/dashboard/project/<your-project>/sql/new )
-- =====================================================================

-- ── STEP 1: Projects Table ────────────────────────────────────────────────
-- Uses autoincrementing serial integer IDs (not UUIDs).
-- Scoped per user via FK to public.users.
CREATE TABLE IF NOT EXISTS public.projects (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Index for fetching a user's projects quickly
CREATE INDEX IF NOT EXISTS idx_projects_user_id
    ON public.projects (user_id);


-- ── STEP 2: Project Tasks (Checklist) Table ───────────────────────────────
-- Uses autoincrementing serial integer IDs.
-- Scoped per project via FK to public.projects with CASCADE DELETE,
-- so deleting a project automatically removes all its tasks.
CREATE TABLE IF NOT EXISTS public.project_tasks (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    description  TEXT NOT NULL,
    is_completed BOOLEAN DEFAULT false NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Index for fetching tasks associated with a project rapidly
CREATE INDEX IF NOT EXISTS idx_project_tasks_project_id
    ON public.project_tasks (project_id);


-- ── STEP 3: Row-Level Security ────────────────────────────────────────────
-- Matching the security pattern established in Phase 1 (app-level session validation).
-- Security is enforced inside the app by validating the session token
-- in authService.js before any query is run.
ALTER TABLE public.projects      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tasks DISABLE ROW LEVEL SECURITY;


-- ── STEP 4: Verify the setup ──────────────────────────────────────────────
-- Run these SELECTs after the script to confirm everything looks correct.

-- Should return the table structure for projects:
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'projects'
ORDER BY ordinal_position;

-- Should return the table structure for project_tasks:
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'project_tasks'
ORDER BY ordinal_position;
