import React, { useEffect, useState } from 'react';
import { CloudSun, MapPin, Bell, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuthStore } from '../store/authStore';
import { fetchTodayReminders, saveUserLocation, geocodeCity } from '../lib/remindersService';

/**
 * RemindersCard — Dashboard card that (a) prompts to enable location for
 * weather reminders when none is saved, and (b) lists today's reminders.
 * Weather reminders are generated by the daily cron (api/generate-reminders).
 */
export default function RemindersCard() {
  const { user } = useAuthStore();
  const [reminders, setReminders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [locating, setLocating] = useState(false);
  const [city, setCity] = useState('');
  const hasLocation = Boolean(user?.latitude && user?.longitude);

  useEffect(() => {
    let alive = true;
    if (!user?.id) return;
    fetchTodayReminders(user.id).then((r) => {
      if (alive) {
        setReminders(r);
        setLoading(false);
      }
    });
    return () => {
      alive = false;
    };
  }, [user?.id]);

  const useDeviceLocation = () => {
    if (!navigator.geolocation) {
      toast.error('Geolocation not supported — enter a city instead.');
      return;
    }
    setLocating(true);
    navigator.geolocation.getCurrentPosition(
      async (pos) => {
        const res = await saveUserLocation(user.id, {
          latitude: pos.coords.latitude,
          longitude: pos.coords.longitude,
        });
        setLocating(false);
        toast[res.ok ? 'success' : 'error'](
          res.ok ? 'Location saved — weather reminders enabled.' : res.error,
        );
        if (res.ok) window.location.reload();
      },
      () => {
        setLocating(false);
        toast.error('Location denied — enter a city below instead.');
      },
      { timeout: 10000 },
    );
  };

  const useCity = async () => {
    if (!city.trim()) return;
    setLocating(true);
    const geo = await geocodeCity(city);
    if (!geo) {
      setLocating(false);
      toast.error('Could not find that city.');
      return;
    }
    const res = await saveUserLocation(user.id, {
      latitude: geo.latitude,
      longitude: geo.longitude,
      city: geo.name,
    });
    setLocating(false);
    toast[res.ok ? 'success' : 'error'](res.ok ? `Location set to ${geo.name}.` : res.error);
    if (res.ok) window.location.reload();
  };

  // Nothing to show and location already set → keep the dashboard clean.
  if (!loading && reminders.length === 0 && hasLocation) return null;

  return (
    <div className="bg-white border border-gray-200 rounded-2xl shadow-sm p-4 md:p-5 space-y-3">
      <div className="flex items-center gap-2">
        <Bell size={15} className="text-green-600" />
        <h3 className="text-xs font-bold text-gray-800 uppercase tracking-wide">Reminders</h3>
      </div>

      {loading ? (
        <p className="text-xs text-gray-400 flex items-center gap-1.5">
          <Loader2 size={12} className="animate-spin" /> Loading…
        </p>
      ) : reminders.length > 0 ? (
        <ul className="space-y-2">
          {reminders.map((r) => (
            <li
              key={r.id}
              className="flex items-start gap-2.5 border border-gray-150 bg-green-50/40 rounded-xl px-3 py-2.5"
            >
              <CloudSun size={16} className="text-green-600 mt-0.5 shrink-0" />
              <p className="text-sm text-gray-700 leading-snug">{r.message}</p>
            </li>
          ))}
        </ul>
      ) : null}

      {/* Location enabler — only when no location is saved yet. */}
      {!hasLocation && (
        <div className="border-t border-gray-100 pt-3 space-y-2">
          <p className="text-xs text-gray-500 leading-relaxed flex items-start gap-1.5">
            <MapPin size={13} className="text-amber-500 mt-0.5 shrink-0" />
            Enable location to get weather-aware reminders (e.g. rain before an outdoor task).
          </p>
          <div className="flex flex-col sm:flex-row gap-2">
            <button
              onClick={useDeviceLocation}
              disabled={locating}
              className="bg-green-600 hover:bg-green-700 text-white text-sm font-bold px-4 py-1.5 rounded-lg disabled:opacity-60"
            >
              {locating ? 'Locating…' : 'Use my location'}
            </button>
            <div className="flex gap-2 flex-1">
              <input
                value={city}
                onChange={(e) => setCity(e.target.value)}
                placeholder="or enter a city"
                className="flex-1 border border-gray-300 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:border-green-500"
              />
              <button
                onClick={useCity}
                disabled={locating || !city.trim()}
                className="border border-gray-300 hover:bg-gray-50 text-gray-700 text-sm font-bold px-3 py-1.5 rounded-lg disabled:opacity-60"
              >
                Set
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
